"""Deterministic projections: human-readable, git-diffable markdown.

branches/<b>.md (branch card), canon/CANON.md (SSOT), ledger.md (decision log).
Regenerated by folding the truth; deterministic ordering keeps diffs small.
"""
from __future__ import annotations

from .core import Store, now_iso, safe_float
from . import ops

_GROUPS = [
    ("principle", "Principles"),
    ("decision", "Decisions"),
    ("constraint", "Constraints"),
    ("open_question", "Open questions"),
    ("rejected_path", "Rejected paths"),
    ("preference", "Preferences"),
    ("risk", "Risks"),
    ("fact", "Facts"),
    ("assumption", "Assumptions"),
    ("task", "Tasks"),
    ("artifact", "Artifacts"),
]
_KNOWN_TYPES = {t for t, _ in _GROUPS}


def _render_atoms(atoms: list[dict]) -> str:
    lines = []

    def render_group(title, items):
        lines.append(f"## {title}")
        for a in items:
            tier = a.get("authority_tier", "")
            conf = round(safe_float(a.get("confidence_score"), 0.0), 2)
            lines.append(f"- {a['statement']}  _({tier}, {conf})_")
        lines.append("")

    for _type, title in _GROUPS:
        items = [a for a in atoms if a.get("atom_type") == _type]
        if items:
            render_group(title, items)
    # catch-all so no settled atom is ever silently dropped from the SSOT projection
    other = [a for a in atoms if a.get("atom_type") not in _KNOWN_TYPES]
    if other:
        render_group("Other", other)
    return "\n".join(lines).rstrip() + "\n"


def project_branch(store: Store, branch_id: str) -> str:
    meta = {b["branch_id"]: b for b in ops.list_branches(store)}.get(branch_id, {})
    atoms = ops.current_atoms(store, branch_id, lifecycles=("active", "released"))
    head = store.get_branch_head(branch_id) or ""
    fm = [
        "---",
        f"branch: {branch_id}",
        f"name: {meta.get('name', branch_id)}",
        f"intent: {meta.get('intent', '')}",
        f"status: {meta.get('status', 'active')}",
        f"head: {head}",
        "---",
        "",
        f"# Branch — {meta.get('name', branch_id)}",
        "",
    ]
    body = _render_atoms(atoms) if atoms else "_No tracked atoms yet._\n"
    out = store.dir / "branches" / f"{branch_id}.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    text = "\n".join(fm) + body
    out.write_text(text, encoding="utf-8")
    return str(out)


def project_canon(store: Store) -> str:
    branch_id = store.config().get("canon_branch", "main")
    atoms = ops.current_atoms(store, branch_id, lifecycles=("active", "released"))
    head = [
        "---",
        "doc: canon",
        f"branch: {branch_id}",
        f"head: {store.get_branch_head(branch_id) or ''}",
        "---",
        "",
        "# Canon — the source of truth",
        "",
        "> The agreed context for this project. Branches explore; Canon is what has settled.",
        "",
    ]
    body = _render_atoms(atoms) if atoms else "_Canon is empty. Run `basin save` on a branch._\n"
    out = store.dir / "canon" / "CANON.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(head) + body, encoding="utf-8")
    return str(out)


def append_ledger(store: Store, branch_id: str, message: str, n_promoted: int) -> str:
    out = store.dir / "ledger.md"
    if not out.exists():
        out.write_text("# Decision ledger\n\n", encoding="utf-8")
    with open(out, "a", encoding="utf-8") as f:
        f.write(f"- {now_iso()} · `{branch_id}` · save: {message or '(no message)'} · {n_promoted} atoms promoted\n")
    return str(out)


def project_all(store: Store) -> dict:
    paths = {"branches": [], "canon": project_canon(store)}
    for b in ops.list_branches(store):
        paths["branches"].append(project_branch(store, b["branch_id"]))
    return paths
